### ISSUE TITLE
Add doc

### ISSUE THREAD

**Issue by albertofernandezvillan** [svrbasky/Thermal-Camera-Vitals-Tracker-COVID-19#1]
If I am not wrong, I have seen that you have published a nice article here (https://medium.com/@svrbasky/thermal-imaging-based-vitals-monitoring-to-track-covid-19-without-compromising-privacy-1079d54d1987) explaining how the algorithm works.
Could you add the link to this repo as a minimal documentation. I think this could help a lot.

**Comment by svrbasky** [comment]
Thanks for pointing out, I did not consider that I could do that.
